In [1]:
import pandas
import pandas as pd

In [2]:
data = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David', None],
    'age': [25, 30,  None, 40, 45],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
})

In [3]:
data

      name   age         city
0    Alice  25.0     New York
1      Bob  30.0  Los Angeles
2  Charlie   NaN      Chicago
3    David  40.0      Houston
4      NaN  45.0      Phoenix

In [4]:
dropna_data = data.dropna()
dropna_data

    name   age         city
0  Alice  25.0     New York
1    Bob  30.0  Los Angeles
3  David  40.0      Houston

In [5]:
len(dropna_data)

3

In [6]:
len(data)

5

In [7]:
data.info

<bound method DataFrame.info of       name   age         city
0    Alice  25.0     New York
1      Bob  30.0  Los Angeles
2  Charlie   NaN      Chicago
3    David  40.0      Houston
4      NaN  45.0      Phoenix>

In [8]:
data.describe()

             age
count   4.000000
mean   35.000000
std     9.128709
min    25.000000
25%    28.750000
50%    35.000000
75%    41.250000
max    45.000000

In [9]:
data.isna()

    name    age   city
0  False  False  False
1  False  False  False
2  False   True  False
3  False  False  False
4   True  False  False

In [10]:
data.isnull()

    name    age   city
0  False  False  False
1  False  False  False
2  False   True  False
3  False  False  False
4   True  False  False

In [11]:
data.isna().sum()

name    1
age     1
city    0
dtype: int64

In [12]:
data.isnull().sum()

name    1
age     1
city    0
dtype: int64

In [13]:
data.isnull().sum().sum()

np.int64(2)

In [14]:
data[data.isna().any(axis=1)]

      name   age     city
2  Charlie   NaN  Chicago
4      NaN  45.0  Phoenix

In [15]:
age_mean = data['age'].mean()
age_mean

np.float64(35.0)

In [16]:
fill_data = data.fillna(({
    'name': 'Unknown',
    'age': age_mean,
    'city': 'Unknown'
}))

In [18]:
fill_data

      name   age         city
0    Alice  25.0     New York
1      Bob  30.0  Los Angeles
2  Charlie  35.0      Chicago
3    David  40.0      Houston
4  Unknown  45.0      Phoenix

In [19]:
ff = data.ffill()
ff

      name   age         city
0    Alice  25.0     New York
1      Bob  30.0  Los Angeles
2  Charlie  30.0      Chicago
3    David  40.0      Houston
4    David  45.0      Phoenix

In [20]:
bf = data.bfill()

In [41]:
bf

      name   age         city
0    Alice  25.0     New York
1      Bob  30.0  Los Angeles
2  Charlie  40.0      Chicago
3    David  40.0      Houston
4      NaN  45.0      Phoenix

In [51]:
# df.loc[行标签, 列标签]
bfi = bf["name"]
bfi = bf.loc[1]
bfi

name            Bob
age            30.0
city    Los Angeles
Name: 1, dtype: object

In [55]:
bfii

name            Bob
age            30.0
city    Los Angeles
Name: 1, dtype: object

In [33]:
bfi

name       Alice
age         1000
city    New York
Name: 0, dtype: object

name       Alice
age      Unknown
city    New York
Name: 0, dtype: object

In [59]:
import pandas as pd
import numpy as np

# ✅ 正确的数据结构
bars = {
    "time": pd.DataFrame(
        {0: [1704067200000], 1: [1704153600000], 2: [1704240000000]},
        index=["000001.SZ"]
    ),
    "open": pd.DataFrame(
        {0: [12.5], 1: [12.7], 2: [12.6]},
        index=["000001.SZ"]
    ),
    "high": pd.DataFrame(
        {0: [12.8], 1: [12.9], 2: [12.7]},
        index=["000001.SZ"]
    ),
    "low": pd.DataFrame(
        {0: [12.3], 1: [12.5], 2: [12.4]},
        index=["000001.SZ"]
    ),
    "close": pd.DataFrame(
        {0: [12.7], 1: [12.6], 2: [12.5]},
        index=["000001.SZ"]
    ),
    "volume": pd.DataFrame(
        {0: [1000000], 1: [1200000], 2: [1100000]},
        index=["000001.SZ"]
    ),
}

In [61]:
bars["time"]

                       0              1              2
000001.SZ  1704067200000  1704153600000  1704240000000

In [63]:
symbol = "000001.SZ"
loc = bars["time"].loc[symbol]

In [64]:
loc

0    1704067200000
1    1704153600000
2    1704240000000
Name: 000001.SZ, dtype: int64

In [65]:
loc = loc.values

In [66]:
loc

array([1704067200000, 1704153600000, 1704240000000])

In [68]:
idx = pd.DatetimeIndex(loc.flatten())
idx

DatetimeIndex(['1970-01-01 00:28:24.067200', '1970-01-01 00:28:24.153600',
               '1970-01-01 00:28:24.240000'],
              dtype='datetime64[ns]', freq=None)

In [69]:
idx = pd.DatetimeIndex(loc)

In [70]:
idx

DatetimeIndex(['1970-01-01 00:28:24.067200', '1970-01-01 00:28:24.153600',
               '1970-01-01 00:28:24.240000'],
              dtype='datetime64[ns]', freq=None)

In [72]:
idx = pd.DatetimeIndex(pd.to_datetime(loc, unit='ms'))
idx

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03'], dtype='datetime64[ms]', freq=None)

In [73]:
_OHLCV_FIELDS = ("open", "high", "low", "close", "volume")
_OHLCV_COLUMNS = ("Open", "High", "Low", "Close", "Volume")
data = {}
for f, col in zip(_OHLCV_FIELDS, _OHLCV_COLUMNS):
    data[col] = bars[f].loc[symbol].values.flatten()
    print(f"{col}: {data[col]}")

Open: [12.5 12.7 12.6]
High: [12.8 12.9 12.7]
Low: [12.3 12.5 12.4]
Close: [12.7 12.6 12.5]
Volume: [1000000 1200000 1100000]

In [74]:
df = pd.DataFrame(data, index=idx)

In [75]:
df

            Open  High   Low  Close   Volume
2024-01-01  12.5  12.8  12.3   12.7  1000000
2024-01-02  12.7  12.9  12.5   12.6  1200000
2024-01-03  12.6  12.7  12.4   12.5  1100000

In [77]:
df = pd.DataFrame(
    {
        "Open": [100, 101, 102, 103, 104],
        "High": [105, 106, 107, 108, 109],
        "Low": [95, 96, 97, 98, 99],
        "Close": [102, 103, 104, 105, 106],
        "Volume": [1000000, 1200000, 1100000, 1300000, 1250000]
    },

)
df

   Open  High  Low  Close   Volume
0   100   105   95    102  1000000
1   101   106   96    103  1200000
2   102   107   97    104  1100000
3   103   108   98    105  1300000
4   104   109   99    106  1250000

In [78]:
row = df.loc[1:3]

In [79]:
row

   Open  High  Low  Close   Volume
1   101   106   96    103  1200000
2   102   107   97    104  1100000
3   103   108   98    105  1300000

In [88]:
col = df.loc[:,"High"]
col

0    105
1    106
2    107
3    108
4    109
Name: High, dtype: int64

In [86]:
close_prices = df.loc[:, "Close"]
close_prices

0    102
1    103
2    104
3    105
4    106
Name: Close, dtype: int64

In [89]:
c = df.iloc[0]
c

Open          100
High          105
Low            95
Close         102
Volume    1000000
Name: 0, dtype: int64

In [93]:
c = df.iloc[[0,2,4]]
c

   Open  High  Low  Close   Volume
0   100   105   95    102  1000000
2   102   107   97    104  1100000
4   104   109   99    106  1250000

In [94]:
c = df.iloc[:, 3]
c

0    102
1    103
2    104
3    105
4    106
Name: Close, dtype: int64

In [95]:
df1 = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
df1

   A  B
0  1  3
1  2  4

In [96]:
print(isinstance(df1, pd.MultiIndex))

False

In [98]:
df2 = pd.DataFrame(
    {("A", "x"): [1, 2], ("A", "y"): [3, 4]}
)
df2

   A
   x  y
0  1  3
1  2  4

In [99]:
df1

   A  B
0  1  3
1  2  4

In [100]:
df1.columns

Index(['A', 'B'], dtype='str')

In [101]:
df1.columns.values

<StringArray>
['A', 'B']
Length: 2, dtype: str

In [102]:
df1.columns.nlevels

1

In [103]:
df2.columns.nlevels

2

In [104]:
columns = pd.MultiIndex.from_tuples([
    ("Open", "AAPL"),
    ("Open", "MSFT"),
    ("Close", "AAPL"),
    ("Close", "MSFT")
])

In [105]:
columns

MultiIndex([( 'Open', 'AAPL'),
            ( 'Open', 'MSFT'),
            ('Close', 'AAPL'),
            ('Close', 'MSFT')],
           )

In [106]:
data = pd.DataFrame(
    {
        ("Open", "AAPL"): [100, 101],
        ("Open", "MSFT"): [200, 201],
        ("Close", "AAPL"): [102, 103],
        ("Close", "MSFT"): [202, 203],
    },
    index=["2024-01-01", "2024-01-02"]
)
data

           Open      Close
           AAPL MSFT  AAPL MSFT
2024-01-01  100  200   102  202
2024-01-02  101  201   103  203

In [108]:
data.columns.nlevels

2

In [109]:
dc = data.droplevel(level=1, axis=1)
dc

            Open  Open  Close  Close
2024-01-01   100   200    102    202
2024-01-02   101   201    103    203